### ISSUE TITLE
OpenAPI Spec update for server variable

### ISSUE THREAD

**Issue by grokify** [ringcentral/engage-digital-api-docs#19]
The server parameter has a variable which should be expanded per OAS3.

Here's an example from the Swagger.io documentation:

https://swagger.io/specification/#server-object-example

```yaml
servers:
- url: https://{username}.gigantic-server.com:{port}/{basePath}
  description: The production API server
  variables:
    username:
      # note! no enum here means it is an open value
      default: demo
      description: this value is assigned by the service provider, in this example `gigantic-server.com`
    port:
      enum:
        - '8443'
        - '443'
      default: '8443'
    basePath:
      # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
      default: v2
```

The current version indicates a variable using angle brackets.

```yaml
servers:
  - url: 'https://<yourdomain>.api.engagement.dimelo.com/1.0'
```
